
identify_task:
    description: >
      Analyze and select the best city for the trip based 
      on weather patterns, seasonal events, and travel costs. 
      Compare multiple cities, considering factors like 
      current weather, upcoming events, and expenses.

      Your final answer must be a detailed report on the chosen city,
      including actual flight costs, weather forecasts, and attractions.
                Traveling from: {origin}
                City Options: {cities}
                Trip Date: {range}
                Traveler Interests: {interests}
    agent: city_selection_agent
    expected_output: >
      A detailed report on the chosen city including costs, weather forecast, and attractions

gather_task:
    description: >
      As a local expert you must compile an in-depth guide 
                for someone traveling to {cities}.
                Gather info on attractions, customs, hidden gems, 
                events, and activity recommendations.

                Trip Date: {range}
                Traveling from: {origin}
                Traveler Interests: {interests}
    agent: local_expert
    expected_output: >
      Comprehensive city guide including hidden gems, cultural hotspots, and practical travel tips

plan_task:
    description: >
      Expand this guide into a full 7-day travel 
                itinerary with detailed per-day plans, including 
                weather forecasts, places to eat, packing suggestions, 
                and a budget breakdown.
                
                You MUST suggest actual places to visit, actual hotels 
                to stay and actual restaurants to go to.
                
                This itinerary should cover all aspects of the trip, 
                from arrival to departure, integrating the city guide
                information with practical travel logistics.
                
                Your final answer MUST be a complete expanded travel plan,
                formatted as markdown, encompassing a daily schedule,
                anticipated weather conditions, recommended clothing and
                items to pack, and a detailed budget, ensuring THE BEST
                TRIP EVER. Be specific and give it a reason why you picked
                each place, what makes them special! 

                Trip Date: {range}
                Traveling from: {origin}
                Traveler Interests: {interests}
    agent: travel_concierge
    expected_output: >
      Complete expanded travel plan with daily schedule, weather conditions, packing suggestions, and budget breakdown
